<script>
	import "./Main.css";
	const tips = [
		'Create a budget and track your expenses.',
		'Set financial goals and stick to them.',
		'Cut unnecessary expenses and review your spending regularly.',
		'Avoid impulse buying by planning your purchases.',
		'Save at least 20% of your income.',
		'Avoid using credit cards for non-essential purchases.',
		'Limit dining out and cook meals at home.',
		'Track your spending habits and identify areas to save.',
		'Shop around for better deals and discounts.',
		'Use coupons and cash-back offers to save money.',
		'Buy in bulk for non-perishable items.',
		'Consider second-hand items to save money.',
		'Plan meals ahead of time to avoid food waste.',
		'Cancel subscriptions you don’t use anymore.',
		'Compare energy providers and find the best deals.',
		'Install energy-efficient appliances to reduce electricity bills.',
		'Turn off lights when not in use.',
		'Unplug electronics to prevent energy waste.',
		'Install a programmable thermostat to save on heating/cooling.',
		'Take public transport or carpool to save on commuting costs.',
		'Maintain your vehicle to avoid expensive repairs.',
		'Reduce water usage to lower utility bills.',
		'Switch to LED bulbs to save on electricity.',
		'Switch to a high-yield savings account for better interest rates.',
		'Avoid payday loans and high-interest debt.',
		'Pay off debt as soon as possible to avoid accumulating interest.',
		'Consolidate your debts to lower your monthly payments.',
		'Build an emergency fund for unexpected expenses.',
		'Set up automatic transfers to your savings account.',
		'Take advantage of retirement savings plans like 401(k)s or IRAs.',
		'Take full advantage of employer benefits, like health insurance and 401(k) matching.',
		'Shop around for insurance and find the best rates.',
		'Review your insurance coverage regularly.',
		'Increase your insurance deductibles to lower premiums.',
		'Use apps to track your spending and manage your finances.',
		'Automate bill payments to avoid late fees.',
		'Check your credit report regularly to spot errors.',
		'Improve your credit score to secure better financial deals.',
		'Pay bills on time to avoid late fees and penalties.',
		'Use credit cards with rewards and redeem them for savings.',
		'Use cashback apps to save on everyday purchases.',
		'Sell unused items to earn extra cash.',
		'Borrow or rent instead of buying things you don’t need.',
		'Use the library for books and other media instead of buying them.',
		'Take advantage of free community events and activities.',
		'Exercise at home using free resources, avoiding gym memberships.',
		'Look for discounts, including student, senior, or military discounts.',
		'Plan vacations in advance to secure cheaper flights and accommodations.',
		'Travel during off-peak seasons to save on flights and hotels.',
		'Use travel rewards and loyalty programs to save money.',
		'Stay in budget accommodations when traveling.',
		'Cook while traveling to save on food expenses.',
		'Limit alcohol consumption to save money while socializing.',
		'Quit smoking to save on costly habits and improve health.',
		'Avoid gambling and other risky financial activities.',
		'Limit entertainment expenses by using free options.',
		'Host potlucks or gatherings at home instead of dining out.',
		'DIY home repairs to avoid expensive professional services.',
		'Give homemade gifts instead of buying expensive ones.',
		'Use reusable products to reduce waste and save money.',
		'Make your own cleaning products instead of buying them.',
		'Use a clothesline to dry clothes and save on energy costs.',
		'Repair items instead of replacing them to reduce expenses.',
		'Buy quality items that last longer and save in the long run.',
		'Avoid fast fashion by buying timeless and durable clothing.',
		'Invest in experiences, not material things, for lasting satisfaction.',
		'Stay focused on your financial goals and stay motivated.',
		'Track your progress and celebrate small financial victories.',
		'Review your spending at the end of every month and adjust your budget.',
		'Avoid lifestyle inflation as your income increases.'
	];
</script>
<div class="tip-container">
	<h1>Golden Financial Tip</h1>
	<p>{tips[Math.floor(Math.random() * tips.length)]}</p>
</div>